os:
  - linux
dist: bionic
services:
  - xvfb
language: node_js
node_js:
  - "10"
  - "8"
before_install:
  - "if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install metacity; fi"
  - "if [[ $TRAVIS_OS_NAME == 'linux' ]]; then metacity --sm-disable --replace 2> metacity.err & fi"
  - "if [[ $TRAVIS_OS_NAME == 'linux' ]]; then metacity-theme-viewer & fi"
script:
  - npm test
