os:
  - linux
dist: bionic
services:
  - xvfb
language: node_js
node_js:
  - '10'
  - '8'
install: true
addons:
  apt:
    packages:
    - metacity
before_script:
  - "if [[ $TRAVIS_OS_NAME == 'linux' ]]; then metacity --sm-disable --replace 2> metacity.err & fi"
  - "if [[ $TRAVIS_OS_NAME == 'linux' ]]; then metacity-theme-viewer & fi"
script:
  - npm install
  - npm test
